/* AUTO-GENERATED by scripts/extract-glossary.mjs — do not edit by hand.
 * Source: translations.html  ·  185 curated audiology phrase pairs.
 * Re-run `npm run extract-glossary` after editing translations.html, then redeploy.
 */
export default [
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "I",
    "vi": "Tôi",
    "note": "Neutral — used with peers or people younger"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "I",
    "vi": "Tớ",
    "note": "Casual, amongst friends"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "We",
    "vi": "Mình",
    "note": "Informal, used among close friends or peers"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "We",
    "vi": "Chúng tôi",
    "note": "\"We\" — not including listener"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "We",
    "vi": "Chúng ta",
    "note": "\"We\" — including speaker and listener"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "(pronoun)",
    "vi": "Anh",
    "note": "Older male & similar age"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "(pronoun)",
    "vi": "Chị",
    "note": "Older female & similar age"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "(pronoun)",
    "vi": "Em",
    "note": "Younger person & similar age"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "(pronoun)",
    "vi": "Chú",
    "note": "Older male / uncle age"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "(pronoun)",
    "vi": "Cô",
    "note": "Older female / aunt age"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "(pronoun)",
    "vi": "Ông",
    "note": "Grandpa age"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "(pronoun)",
    "vi": "Bà",
    "note": "Grandma age"
  },
  {
    "category": "pronouns",
    "subsection": "Vietnamese Pronouns",
    "en": "(pronoun)",
    "vi": "Con",
    "note": "Used when addressing a child, or by yourself to elders"
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Hello",
    "vi": "Chào bạn."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "My name is…",
    "vi": "Tôi tên là…"
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Nice to meet you.",
    "vi": "Rất vui được gặp bạn."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "How are you doing today?",
    "vi": "Hôm nay bạn thế nào?"
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Please follow me.",
    "vi": "Xin theo tôi."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "You can have a seat here.",
    "vi": "Mời bạn ngồi ở đây."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Please have a seat.",
    "vi": "Mời bạn ngồi."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Do you have any questions before we begin?",
    "vi": "Bạn có câu hỏi nào trước khi chúng ta bắt đầu không?"
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Please let me know if you feel uncomfortable at any time.",
    "vi": "Nếu có gì làm bạn không thoải mái, hãy báo cho tôi biết."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "If you need anything, feel free to ask.",
    "vi": "Bạn cần gì cứ nói với tôi."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Please let me know if you ever need to take a break during our testing.",
    "vi": "Nếu bạn muốn nghỉ giữa chừng, cứ nói với tôi."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Take care.",
    "vi": "Bạn nhớ giữ gìn sức khỏe nhé."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Have a good day.",
    "vi": "Chúc bạn một ngày tốt lành."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Hope all goes well.",
    "vi": "Hy vọng mọi việc đều tốt đẹp."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "Thank you.",
    "vi": "Cám ơn bạn."
  },
  {
    "category": "greetings",
    "subsection": "Greetings & Common Phrases",
    "en": "You're welcome.",
    "vi": "Không có gì. / Không có chi."
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "What brings you in today?",
    "vi": "Hôm nay bạn tới đây vì chuyện gì?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "How long have you had this problem?",
    "vi": "Bạn bị vấn đề này bao lâu rồi?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "When did you start having this problem?",
    "vi": "Bạn gặp vấn đề này từ khi nào?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have trouble hearing?",
    "vi": "Bạn có gặp khó khăn khi nghe không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Have you had your hearing tested before?",
    "vi": "Bạn đã từng kiểm tra thính lực chưa?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "When?",
    "vi": "Khi nào? / Lúc nào?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Where?",
    "vi": "Ở đâu? / Chỗ nào?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Have you noticed any changes in your hearing recently?",
    "vi": "Gần đây bạn có nhận thấy sự thay đổi nào trong thính lực không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "In what situations do you have trouble hearing?",
    "vi": "Bạn gặp khó khăn khi nghe trong những hoàn cảnh nào?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "At restaurants?",
    "vi": "Ở nhà hàng?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "At parties?",
    "vi": "Ở mấy buổi tiệc?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "At work?",
    "vi": "Ở việc làm?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have trouble hearing in noisy environments?",
    "vi": "Bạn có gặp khó khăn khi nghe trong môi trường ồn ào không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have trouble hearing when talking on the phone?",
    "vi": "Bạn có gặp khó khăn khi nói chuyện trên điện thoại không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have a history of noise exposure?",
    "vi": "Bạn có từng ở trong môi trường ồn ào trong thời gian dài không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Are you exposed to a lot of loud noise at work?",
    "vi": "Bạn có làm việc trong môi trường ồn ào không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you use hearing protection?",
    "vi": "Bạn có mang đồ bảo vệ tai khi ở nơi ồn ào không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have ear pain?",
    "vi": "Bạn có bị đau tai không? / Bạn có bị nhức tai không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have a history of ear infections?",
    "vi": "Bạn có thường xuyên bị viêm tai trước đây không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Any recent ear infections?",
    "vi": "Bạn có bị viêm tai mới đây không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Have you had any ear surgeries?",
    "vi": "Bạn có bao giờ mổ tai chưa?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Have you been to an ear nose and throat physician before?",
    "vi": "Bạn đã từng đi khám bác sĩ tai mũi họng chưa?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have tinnitus or ringing in your ears?",
    "vi": "Bạn có bị ù tai không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Is your tinnitus bothersome?",
    "vi": "Ù tai có làm bạn khó chịu không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have dizziness or balance issues?",
    "vi": "Bạn có bị chóng mặt hoặc mất thăng bằng không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Have you fallen before?",
    "vi": "Bạn có bao giờ té chưa? / Bạn đã từng bị té ngã chưa?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Is there a history of hearing loss in your family?",
    "vi": "Gia đình bạn có tiền sử mất thính lực không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Is there a history of childhood hearing loss in your family?",
    "vi": "Gia đình của bạn có tiền sử mất thính lực từ khi còn nhỏ không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Are you currently taking any medications?",
    "vi": "Hiện tại bạn có đang dùng thuốc gì không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Any major medical changes within the past year?",
    "vi": "Trong năm qua, bạn có thay đổi gì lớn về sức khỏe không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Have you ever worn hearing aids before?",
    "vi": "Bạn đã từng đeo máy trợ thính chưa?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Have you served in the military?",
    "vi": "Bạn có từng làm quân nhân không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Is there anything else you would like to share about your hearing or ear health?",
    "vi": "Bạn có muốn chia sẻ thêm gì về thính lực hoặc sức khỏe tai không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Anything else you want to share before we get started?",
    "vi": "Bạn còn muốn chia sẻ điều gì nữa trước khi chúng ta bắt đầu không?"
  },
  {
    "category": "history",
    "subsection": "Case History Questions",
    "en": "Do you have any questions for me?",
    "vi": "Bạn có câu hỏi nào cho tôi không?"
  },
  {
    "category": "testing",
    "subsection": "Test Order",
    "en": "The first test is…",
    "vi": "Kiểm tra đầu tiên là…"
  },
  {
    "category": "testing",
    "subsection": "Test Order",
    "en": "Next is…",
    "vi": "Tiếp theo là…"
  },
  {
    "category": "testing",
    "subsection": "Test Order",
    "en": "For this next test…",
    "vi": "Cho bài kiểm tra tiếp theo này…"
  },
  {
    "category": "testing",
    "subsection": "Test Order",
    "en": "For our last test…",
    "vi": "Cho bài kiểm tra cuối cùng này…"
  },
  {
    "category": "testing",
    "subsection": "Test Order",
    "en": "One more test.",
    "vi": "Chỉ còn một kiểm tra nữa."
  },
  {
    "category": "testing",
    "subsection": "Test Order",
    "en": "Almost done.",
    "vi": "Sắp xong rồi."
  },
  {
    "category": "testing",
    "subsection": "Test Order",
    "en": "We are all done.",
    "vi": "Chúng ta đã hoàn tất."
  },
  {
    "category": "testing",
    "subsection": "Otoscopy",
    "en": "I am going to look in your ears now.",
    "vi": "Tôi sẽ kiểm tra tai của bạn bây giờ."
  },
  {
    "category": "testing",
    "subsection": "Otoscopy",
    "en": "Please sit still and keep your head straight.",
    "vi": "Xin hãy ngồi yên và giữ thẳng đầu."
  },
  {
    "category": "testing",
    "subsection": "Otoscopy",
    "en": "I am gently going to pull on your ear to get a better view.",
    "vi": "Tôi sẽ nhẹ nhàng kéo tai bạn để nhìn rõ hơn."
  },
  {
    "category": "testing",
    "subsection": "Otoscopy",
    "en": "Let me know if you feel any discomfort.",
    "vi": "Hãy cho tôi biết nếu bạn cảm thấy khó chịu."
  },
  {
    "category": "testing",
    "subsection": "Otoscopy",
    "en": "Everything looks normal.",
    "vi": "Mọi thứ trông bình thường."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "Tympanometry is a quick test to see how well your eardrum is moving.",
    "vi": "Đo-độ-rung-nhĩ là một bài kiểm tra nhanh để xem màng nhĩ của bạn đang chuyển động tốt như thế nào."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "This test makes sure that no fluid is built up behind your eardrum.",
    "vi": "Bài kiểm tra này đảm bảo không có dịch tích tụ phía sau màng nhĩ."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "I am going to put this probe into your ear.",
    "vi": "Tôi sẽ đặt đầu dò này vào tai bạn."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "You might hear a tone.",
    "vi": "Bạn có thể nghe thấy một âm thanh."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "You will feel a little bit of pressure.",
    "vi": "Bạn sẽ cảm thấy một chút áp lực."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "The pressure is similar to when you are going up in an airplane.",
    "vi": "Áp suất tương tự như khi bạn đi máy bay."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "This won't hurt.",
    "vi": "Kiểm tra này sẽ không đau."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "Please sit still and quiet.",
    "vi": "Xin bạn hãy ngồi yên và giữ im lặng."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "You don't need to do anything for this test.",
    "vi": "Bạn không cần làm gì cho bài kiểm tra này."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "You can just sit back and relax.",
    "vi": "Bạn chỉ cần ngồi xuống và thư giãn."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "It will be over in just a few seconds.",
    "vi": "Bài kiểm tra sẽ kết thúc chỉ sau vài giây."
  },
  {
    "category": "testing",
    "subsection": "Tympanometry",
    "en": "If you feel uncomfortable at any point, let me know, and I can stop the test.",
    "vi": "Nếu bạn cảm thấy không thoải mái ở bất kỳ thời điểm nào, hãy cho tôi biết và tôi có thể dừng bài kiểm tra."
  },
  {
    "category": "testing",
    "subsection": "Speech Recognition Threshold (SRT)",
    "en": "I will be putting these headphones/inserts on your ears.",
    "vi": "Tôi sẽ đeo tai nghe này vào tai bạn."
  },
  {
    "category": "testing",
    "subsection": "Speech Recognition Threshold (SRT)",
    "en": "I will test one ear at a time.",
    "vi": "Tôi sẽ kiểm tra từng tai một."
  },
  {
    "category": "testing",
    "subsection": "Speech Recognition Threshold (SRT)",
    "en": "For this test I will be saying words like \"doctor,\" \"family,\" and \"work.\"",
    "vi": "Trong bài kiểm tra này, tôi sẽ nói các từ như \"bác sĩ,\" \"gia đình,\" và \"công việc.\""
  },
  {
    "category": "testing",
    "subsection": "Speech Recognition Threshold (SRT)",
    "en": "Try your best to repeat the words back, even if it gets quieter and quieter.",
    "vi": "Hãy cố gắng lặp lại các từ, ngay cả khi âm thanh ngày càng nhỏ hơn."
  },
  {
    "category": "testing",
    "subsection": "Speech Recognition Threshold (SRT)",
    "en": "It is okay to guess.",
    "vi": "Bạn có thể đoán nếu không chắc."
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "You will hear a series of beeps through the headphones.",
    "vi": "Bạn sẽ nghe thấy một loạt tiếng bíp qua tai nghe."
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "Please say \"yes\" when you hear the beep.",
    "vi": "Vui lòng trả lời \"Có\" khi bạn nghe thấy tiếng bíp."
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "Please raise your hand when you hear the beep.",
    "vi": "Vui lòng giơ tay khi nghe thấy tiếng bíp."
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "Please press the button when you hear the beep.",
    "vi": "Vui lòng nhấn nút khi bạn nghe thấy tiếng bíp."
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "Even if the beep is very soft, please say yes / raise your hand / press the button.",
    "vi": "Ngay cả khi tiếng bíp rất nhỏ, vui lòng nói \"có\" / giơ tay / nhấn nút."
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "Even if you are unsure you heard the beep, please say yes.",
    "vi": "Ngay cả khi bạn không chắc mình đã nghe thấy tiếng bíp, hãy trả lời \"có.\""
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "Did you hear the beep?",
    "vi": "Bạn có nghe thấy tiếng bíp không?"
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "For this next test I will go in and change out your headband.",
    "vi": "Trong bài kiểm tra tiếp theo, tôi sẽ vào và thay băng đô cho bạn."
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "I will now place this headband on you.",
    "vi": "Bây giờ tôi sẽ đeo băng đô này cho bạn."
  },
  {
    "category": "testing",
    "subsection": "Pure Tone Audiometry",
    "en": "Continue saying yes when you hear the beeps.",
    "vi": "Tiếp tục trả lời \"có\" khi nghe thấy tiếng bíp."
  },
  {
    "category": "testing",
    "subsection": "Masking",
    "en": "Right ear",
    "vi": "Tai bên phải"
  },
  {
    "category": "testing",
    "subsection": "Masking",
    "en": "Left ear",
    "vi": "Tai bên trái"
  },
  {
    "category": "testing",
    "subsection": "Masking",
    "en": "You might hear some wind noise in your right ear during this test.",
    "vi": "Bạn có thể nghe thấy tiếng gió ở tai phải trong quá trình kiểm tra này."
  },
  {
    "category": "testing",
    "subsection": "Masking",
    "en": "You might hear some wind noise in your left ear during this test.",
    "vi": "Bạn có thể nghe thấy tiếng gió ở tai trái trong quá trình kiểm tra này."
  },
  {
    "category": "testing",
    "subsection": "Masking",
    "en": "Ignore the noise and focus on the words in your right ear.",
    "vi": "Bỏ qua tiếng ồn và tập trung vào những từ ngữ ở tai phải."
  },
  {
    "category": "testing",
    "subsection": "Masking",
    "en": "Ignore the noise and focus on the words in your left ear.",
    "vi": "Bỏ qua tiếng ồn và tập trung vào những từ ngữ ở tai trái."
  },
  {
    "category": "testing",
    "subsection": "Masking",
    "en": "Ignore the noise and focus on the beeps in your right ear.",
    "vi": "Bỏ qua tiếng ồn và tập trung vào tiếng bíp ở tai phải."
  },
  {
    "category": "testing",
    "subsection": "Masking",
    "en": "Ignore the noise and focus on the beeps in your left ear.",
    "vi": "Bỏ qua tiếng ồn và tập trung vào tiếng bíp ở tai trái."
  },
  {
    "category": "testing",
    "subsection": "Word Recognition Score (WRS)",
    "en": "You will hear a man's voice, and he will say things like…",
    "vi": "Bạn sẽ nghe thấy giọng nói của một người đàn ông, và anh ta sẽ nói những điều như…"
  },
  {
    "category": "testing",
    "subsection": "Word Recognition Score (WRS)",
    "en": "You will hear a woman's voice, and she will say things like…",
    "vi": "Bạn sẽ nghe thấy giọng nói của một người phụ nữ, và cô ấy sẽ nói những điều như…"
  },
  {
    "category": "testing",
    "subsection": "Word Recognition Score (WRS)",
    "en": "You will hear a person's voice, and they will say things like…",
    "vi": "Bạn sẽ nghe thấy giọng nói của một người, và họ sẽ nói những điều như…"
  },
  {
    "category": "testing",
    "subsection": "Word Recognition Score (WRS)",
    "en": "You will hear me say \"Say the word ___.\"",
    "vi": "Bạn sẽ nghe tôi nói \"Nói từ ___.\""
  },
  {
    "category": "testing",
    "subsection": "Word Recognition Score (WRS)",
    "en": "\"Say the word ___.\"",
    "vi": "\"Nói từ ___.\""
  },
  {
    "category": "testing",
    "subsection": "Word Recognition Score (WRS)",
    "en": "All you need to do is repeat the last word back to me.",
    "vi": "Bạn chỉ cần lặp lại từ cuối cùng cho tôi."
  },
  {
    "category": "testing",
    "subsection": "Word Recognition Score (WRS)",
    "en": "You will hear some words, please repeat them back.",
    "vi": "Bạn sẽ nghe một số từ, hãy lặp lại chúng."
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Conductive Hearing Loss",
    "vi": "Mất thính lực dẫn truyền"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Sensorineural Hearing Loss",
    "vi": "Mất thính lực thần kinh cảm giác"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Mixed Hearing Loss",
    "vi": "Mất thính lực hỗn hợp"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Sudden Sensorineural Hearing Loss",
    "vi": "Mất thính lực thần kinh cảm giác đột ngột"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Presbycusis",
    "vi": "Suy giảm thính lực do tuổi già"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Noise-Induced Hearing Loss",
    "vi": "Mất thính lực do tiếng ồn"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Auditory Neuropathy Spectrum Disorder (ANSD)",
    "vi": "Rối loạn phổ thần kinh thính giác"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Otitis Media",
    "vi": "Viêm tai giữa"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Otosclerosis",
    "vi": "Xơ cứng tai"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Cholesteatoma",
    "vi": "U nang biểu bì tai"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Eustachian Tube Dysfunction",
    "vi": "Rối loạn vòi nhĩ / Rối loạn chức năng vòi nhĩ"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Meniere's Disease",
    "vi": "Bệnh Meniere"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Benign Paroxysmal Positional Vertigo (BPPV)",
    "vi": "Chóng mặt tư thế kịch phát lành tính"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Auditory Processing Disorder (APD)",
    "vi": "Rối loạn xử lý thính giác"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Tinnitus",
    "vi": "Ù tai"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Barotrauma",
    "vi": "Chấn thương do áp suất"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Hyperacusis",
    "vi": "Nhạy cảm quá mức với âm thanh"
  },
  {
    "category": "diagnoses",
    "subsection": "Hearing-Related Diagnoses",
    "en": "Misophonia",
    "vi": "Chứng ghét âm thanh"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Angina",
    "vi": "Đau thắt ngực"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Arthritis",
    "vi": "Viêm khớp"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Asthma",
    "vi": "Hen suyễn"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Bipolar Disorder",
    "vi": "Rối loạn tâm thần lưỡng cực"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Cancer",
    "vi": "Ung thư"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Cardiovascular Disease",
    "vi": "Bệnh tim mạch"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Hypertension",
    "vi": "Huyết áp cao"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Stroke",
    "vi": "Đột quỵ"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Chronic Obstructive Pulmonary Disorder (COPD)",
    "vi": "Bệnh phổi tắc nghẽn mãn tính"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Depression",
    "vi": "Trầm cảm"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Diabetes",
    "vi": "Tiểu đường"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Fibromyalgia",
    "vi": "Đau cơ"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Multiple Sclerosis",
    "vi": "Suy giảm thần kinh đa dạng"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Osteoporosis",
    "vi": "Loãng xương"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Chronic Kidney Disease",
    "vi": "Bệnh thận mãn tính"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Amyotrophic Lateral Sclerosis (ALS)",
    "vi": "Đứng teo cơ"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Crohn's Disease",
    "vi": "Bệnh Crohn"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Ulcerative Colitis",
    "vi": "Viêm loét đại tràng"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Irritable Bowel Syndrome",
    "vi": "Hội chứng ruột kích thích"
  },
  {
    "category": "diagnoses",
    "subsection": "Other Medical Conditions",
    "en": "Cystic Fibrosis",
    "vi": "Bệnh xơ nang"
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "Based on your hearing test results…",
    "vi": "Dựa trên kết quả đo thính lực của bạn…"
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "Based on today's testing…",
    "vi": "Dựa trên kết quả kiểm tra hôm nay…"
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "You have normal hearing.",
    "vi": "Bạn có thính lực bình thường."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "You have a mild hearing loss.",
    "vi": "Bạn bị mất thính lực nhẹ."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "You have a moderate hearing loss.",
    "vi": "Bạn bị mất thính lực trung bình."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "You have a moderately-severe hearing loss.",
    "vi": "Bạn bị mất thính lực trung bình-nặng."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "You have a severe hearing loss.",
    "vi": "Bạn bị mất thính lực nặng."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "You have a profound hearing loss.",
    "vi": "Bạn bị mất thính lực sâu sắc."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "In both ears.",
    "vi": "Ở cả hai tai."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "In one ear.",
    "vi": "Ở một tai."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "In your right ear.",
    "vi": "Ở tai phải của bạn."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "In your left ear.",
    "vi": "Ở tai trái của bạn."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "In the higher pitches.",
    "vi": "Ở những âm vực cao hơn."
  },
  {
    "category": "results",
    "subsection": "Explaining Results",
    "en": "In the low pitches.",
    "vi": "Ở những âm vực thấp."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "X's are your left ear.",
    "vi": "Dấu X là tai trái của bạn."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "O's are your right ear.",
    "vi": "Dấu O là tai phải của bạn."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "Going from the left to the right of the graph, we go from low pitches to high pitches.",
    "vi": "Từ trái sang phải của biểu đồ, chúng ta đi từ âm vực thấp đến âm vực cao."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "What we consider normal hearing is what lies above this dark line.",
    "vi": "Những gì chúng ta coi là thính lực bình thường nằm ở phía trên đường đậm này."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "What we consider normal hearing is what lies in this shaded area.",
    "vi": "Những gì chúng ta coi là thính lực bình thường nằm ở vùng bóng mờ này."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "Hearing loss usually begins in the higher pitches.",
    "vi": "Mất thính lực thường bắt đầu ở những âm vực cao."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "Hearing loss in the high pitches makes speech less clear and sharp.",
    "vi": "Mất thính lực ở những tần số cao độ, lời nói kém rõ ràng và sắc nét hơn."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "Missing those sounds can make speech less clear and harder to understand.",
    "vi": "Việc thiếu những âm thanh đó có thể khiến lời nói kém rõ ràng và khó hiểu hơn."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "These lower pitches are where vowels are.",
    "vi": "Những âm vực thấp này là nơi chứa các nguyên âm."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "Vowels are what gives us volume.",
    "vi": "Nguyên âm tạo nên âm lượng."
  },
  {
    "category": "results",
    "subsection": "Audiogram Explanation",
    "en": "You can hear that someone is talking, but might have trouble understanding all of what is said.",
    "vi": "Bạn có thể vẫn nghe được lời nói, nhưng có thể gặp khó khăn trong việc hiểu tất cả những gì được nói."
  },
  {
    "category": "results",
    "subsection": "Recommendations",
    "en": "I recommend hearing aids to improve your ability to hear and communicate.",
    "vi": "Tôi khuyên bạn nên dùng máy trợ thính để cải thiện khả năng nghe và giao tiếp."
  },
  {
    "category": "results",
    "subsection": "Recommendations",
    "en": "With hearing aids, you'll be able to hear the speech sounds you've been missing, which will improve clarity in communication.",
    "vi": "Với máy trợ thính, bạn sẽ có thể nghe được những âm thanh lời nói mà bạn đã bỏ lỡ, điều này sẽ cải thiện độ rõ ràng trong giao tiếp."
  },
  {
    "category": "results",
    "subsection": "Recommendations",
    "en": "I recommend seeing an ENT specialist for further evaluation.",
    "vi": "Tôi khuyên bạn nên đến gặp bác sĩ chuyên gia tai mũi họng để được đánh giá thêm."
  },
  {
    "category": "results",
    "subsection": "Recommendations",
    "en": "I recommend that you wear hearing protection when in loud environments.",
    "vi": "Tôi khuyên bạn nên đeo thiết bị bảo vệ thính giác khi ở trong môi trường ồn ào."
  }
];
